export const projects = [
  {
    title: "AI-SDLC Framework",
    slug: "ai-sdlc-framework",
    description: `Experimental framework that adapts traditional Software Development Life Cycle (SDLC) principles for human-AI team collaboration, based on ISO 12207 standards.`,
    shortDescription: `Experimental framework for human-AI team collaboration in software development.`,
    href: "/projects/ai-sdlc-framework",
    externalUrl: "https://github.com/mouimet-infinisoft/AISDLC",
    mediaSrc: "/project-garden.mp4",
    mediaType: "video",
    technologies: ["ISO 12207", "Software Engineering", "AI Collaboration", "SDLC"],
    status: "Active Development",
    year: "2024",
  },
  {
    title: "So Simple Platform",
    slug: "so-simple-platform",
    description: `Enterprise-grade web application for managing social service operations, built using voice-driven AI-SDLC methodology. Features multi-tenant architecture, workflow automation, and comprehensive case management.`,
    shortDescription: `Social services management platform built with voice-driven AI-SDLC methodology.`,
    href: "/projects/so-simple-platform",
    externalUrl: "https://github.com/mouimet-infinisoft/rqrsda2025",
    demoUrl: "https://sisimple.vercel.app/",
    mediaSrc: "/project-notion.png",
    mediaType: "image",
    technologies: ["Next.js 15", "React 19", "Supabase", "PostgreSQL", "Tailwind CSS", "N8N"],
    status: "MVP Ready",
    year: "2024",
  },
  {
    title: "Infinisoft World",
    slug: "infinisoft-world",
    description: `Technology company delivering enterprise-grade software across finance, healthcare, retail, and transportation sectors. 25-person team specializing in AI and cloud solutions.`,
    shortDescription: `Technology company specializing in AI and cloud solutions.`,
    href: "/projects/infinisoft-world",
    externalUrl: "https://infinisoft.world",
    mediaSrc: "/project-pejobs.png",
    mediaType: "image",
    technologies: ["AI Solutions", "Cloud Computing", "Enterprise Software", "Fintech", "Healthcare"],
    status: "Established Company",
    year: "2019",
  },
];
